replicaCount: 3

image:
  repository: quay.io/prometheus/alertmanager
  tag: v0.26.0
  pullPolicy: IfNotPresent

podAnnotations: {}

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true

service:
  type: ClusterIP
  port: 9093

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  storageClass: gp3-csi
  accessModes:
    - ReadWriteOnce
  size: 2Gi

alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: default
    receivers:
      - name: default
    inhibit_rules: []

  # Mount config as a secret
  configMapOverrideName: ""
  configSecret: alertmanager-config
  useExistingSecret: true

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: alertmanager.cloudmasa.app
      paths:
        - path: /
          pathType: Prefix
  tls: []

testFramework:
  enabled: false
  image:
    repository: busybox
    tag: latest
    pullPolicy: IfNotPresent
